Cyrillvorfolomeev/pra 28 work out the visual part of the game
firetimeloop/battlegrad pull request #11
Opened 2023-05-15 07:20 UTC by firetimeloop

### Добавил коллайдеры

![image](https://github.com/firetimeloop/battlegrad/assets/42745928/f094c815-2beb-4eef-82cf-c65ce08f087d)

2023-05-16 18:47 UTC, ElvgOvadykov approved these changes

2023-05-17 06:02 UTC, Shamarash commented on packages/client/src/components/Game/utils/level.ts
> +    switch (lastKey) {
может оставить один цикл? и внутри сделаем switch case, можно будет часть кода сократить

```suggestion
    if (Object.values<string>(MOVE_CONTROL_KEYS).includes(lastKey)) {
      for (const collider of possibleCellColliders) {
        const [colliderStartX, colliderStartY, colliderEndX, colliderEndY] = collider;

        switch (lastKey) {
          case MOVE_CONTROL_KEYS.LEFT: {
            const isCollidingWithTopRightCorner = (
              nextX <= colliderEndX
              && nextY >= colliderStartY
              && nextY <= colliderEndY
            );
            const isCollidingWithBottomRightCorner = (
              nextX <= colliderEndX
              && (nextY + TANK_SIZE) >= colliderStartY
              && (nextY + TANK_SIZE) <= colliderEndY
            );
            isColliding = isCollidingWithTopRightCorner || isCollidingWithBottomRightCorner;
            break;
          }
          case MOVE_CONTROL_KEYS.RIGHT: {
            const isCollidingWithTopLeftCorner = (
              nextX + TANK_SIZE >= colliderStartX
              && nextY >= colliderStartY
              && nextY <= colliderEndY
            );
            const isCollidingWithBottomLeftCorner = (
              nextX + TANK_SIZE >= colliderStartX
              && (nextY + TANK_SIZE) >= colliderStartY
              && (nextY + TANK_SIZE) <= colliderEndY
            );
            isColliding = isCollidingWithTopLeftCorner || isCollidingWithBottomLeftCorner;
            break;
          }
          case MOVE_CONTROL_KEYS.DOWN: {
            const isCollidingWithBottomLeftCorner = (
              nextY + TANK_SIZE >= colliderStartY
              && nextX >= colliderStartX
              && nextX <= colliderEndX
            );
            const isCollidingWithBottomRightCorner = (
              nextY + TANK_SIZE >= colliderStartY
              && (nextX + TANK_SIZE) >= colliderStartX
              && (nextX + TANK_SIZE) <= colliderEndX
            );
            isColliding = isCollidingWithBottomRightCorner || isCollidingWithBottomLeftCorner;
            break;
          }
          case MOVE_CONTROL_KEYS.UP: {
            const isCollidingWithTopLeftCorner = (
              nextY <= colliderEndY
              && nextX >= colliderStartX
              && nextX <= colliderEndX
            );
            const isCollidingWithTopRightCorner = (
              nextY <= colliderEndY
              && (nextX + TANK_SIZE) >= colliderStartX
              && (nextX + TANK_SIZE) <= colliderEndX
            );
            isColliding = isCollidingWithTopLeftCorner || isCollidingWithTopRightCorner;
            break;
          }
          default: break;
        }

        if (isColliding && SHOW_COLLIDERS) {
          colliders.push([
            colliderStartX,
            colliderStartY,
            colliderEndX - colliderStartX,
            colliderEndY - colliderStartY,
          ]);
        }

        if (isColliding) {
          return true;
        }
      }
    }
```

2023-05-17 06:02 UTC, Shamarash commented on packages/client/src/components/Game/utils/level.ts
> +      return;
мне показалось что будет понятнее когда метод с приставкой can возвращает boolean а не boolean | undefined

```suggestion
      return false;
```

2023-05-17 17:07 UTC, firetimeloop commented on packages/client/src/components/Game/utils/level.ts
> +    switch (lastKey) {
Поправил

2023-05-17 17:07 UTC, firetimeloop commented on packages/client/src/components/Game/utils/level.ts
> +      return;
Поправил

2023-05-17 17:46 UTC, Shamarash approved these changes

2023-05-18 08:48 UTC, MikeDevice requested changes

2023-05-18 08:48 UTC, MikeDevice commented on packages/client/src/components/Game/utils/level.ts
> +export let colliders: [number, number, number, number][] = [];
я спрошу то же, что и eslint) Зачем тебе мутабельный экспорт? это потенциальный источник багов

2023-05-18 08:48 UTC, MikeDevice commented on packages/client/src/components/Game/utils/level.ts
> +  colliderBorders: [number, number, number, number];
Много раз дублируешь этот тип. Давай типу `[number, number, number, number]` дадим название

2023-05-18 08:48 UTC, MikeDevice commented on packages/client/src/components/Game/utils/level.ts
> +  canCollide(tank: Tank, lastControlKey: LastControlKey) {
а что такое коллайдер?)

2023-05-18 08:48 UTC, MikeDevice commented on packages/client/src/components/Game/utils/level.ts
> +      .map((cell) => getColliderBorderOnLevel(cell as CellWithoutSprite));
тут не совсем правильно, что тип приходится приводить. Правильно ли я понимаю, что идея в том, что в `getPossibleCollidingCells` лежат и те ячейки, которые со спрайтом, но ты их отфильтровываешь и потому приходится приводить тип, так как остаются только те, что без спрайта?

2023-05-18 08:48 UTC, MikeDevice commented on packages/client/src/components/Game/utils/level.ts
> +          default: break;
в этом `switch` довольно много копи-пасты в каждом `case`. предлагаю общие части вынести во вспомогательные функции или переменные.

2023-05-18 17:57 UTC, firetimeloop commented on packages/client/src/components/Game/utils/level.ts
> +export let colliders: [number, number, number, number][] = [];
Это вначале был служебный массив для разработки, потом понял что нужен для того чтобы все таки рисовать спрайты. Поправлю.

2023-05-18 18:00 UTC, firetimeloop commented on packages/client/src/components/Game/utils/level.ts
> +  canCollide(tank: Tank, lastControlKey: LastControlKey) {
Понял этот коммент как - нужно переделать название в isColliding)

2023-05-18 18:00 UTC, firetimeloop commented on packages/client/src/components/Game/utils/level.ts
> +      .map((cell) => getColliderBorderOnLevel(cell as CellWithoutSprite));
Ага.

2023-05-18 19:13 UTC, firetimeloop commented on packages/client/src/components/Game/utils/level.ts
> +  colliderBorders: [number, number, number, number];
Поправил

2023-05-18 19:14 UTC, firetimeloop commented on packages/client/src/components/Game/utils/level.ts
> +          default: break;
Поправил

2023-05-18 19:16 UTC, MikeDevice commented on packages/client/src/components/Game/utils/level.ts
> +  canCollide(tank: Tank, lastControlKey: LastControlKey) {
нет) я просто не понял, что такое коллайдер)) ну типо я знаю, что такое адронный коллайдер, но как это относится к вашей игре?

2023-05-18 19:17 UTC, MikeDevice approved these changes

2023-05-18 19:22 UTC, firetimeloop commented on packages/client/src/components/Game/utils/level.ts
> +  canCollide(tank: Tank, lastControlKey: LastControlKey) {
А ну это объект который за столкновения отвечает, он невидимый обычно и обычно простой формы, типа круг, квадрат, эллипсоид, а вот сама моделька может иметь геометрию сильно сложнее, таким образом экономят на расчетах физики, в движках тоже есть, ну в Unity точно видел.

2023-05-18 19:24 UTC, MikeDevice commented on packages/client/src/components/Game/utils/level.ts
> +  canCollide(tank: Tank, lastControlKey: LastControlKey) {
ааа. понял. да, я знаю про такие штуки, но знал их всегда по названию "хитбоксы".

2023-05-18 19:41 UTC, firetimeloop commented on packages/client/src/components/Game/utils/level.ts
> +  canCollide(tank: Tank, lastControlKey: LastControlKey) {
Хитбоксами тоже, но чаще вроде игроки так называют, в тех жанрах, где от определения столкновения многое зависит - файтинги, шутеры и т.д. Вот, нашел ссылку в доке юнити - https://docs.unity3d.com/ScriptReference/Collider.html

2023-05-18 19:42 UTC, merged