Shamarash/pra 27 implement the start and end of the game
firetimeloop/battlegrad pull request #14
Opened 2023-05-20 12:00 UTC by Shamarash

Добавлено: 

- коллизия кирпичных стен со снарядами
- взрыв при уничтожении стены
- задержка перед следующим выстрелом, чтобы нельзя было очередью стрелять

https://github.com/firetimeloop/battlegrad/assets/121560956/b25ef9dc-4a1c-42cd-965e-1a05a3a0be14

2023-05-20 12:29 UTC, firetimeloop approved these changes

2023-05-20 12:40 UTC, ElvgOvadykov approved these changes

2023-05-22 07:17 UTC, MikeDevice requested changes

2023-05-22 07:17 UTC, MikeDevice commented on packages/client/src/components/Game/utils/explosion.ts
> +      return [273, 129, 13, 13];
это магические числа, которые стороннему человеку ни о чём не говорят. Вынеси в константы, названия которых будут соответствовать тому, что они значат. или напиши обширные комментарии

2023-05-22 07:17 UTC, MikeDevice commented on packages/client/src/components/Game/utils/projectile.ts
> +        return [346, 102, 4, 3];
то ж самое

2023-05-22 11:11 UTC, Shamarash commented on packages/client/src/components/Game/utils/explosion.ts
> +      return [273, 129, 13, 13];
вынес, назвал как спрайт начало взрыва, середина и конец

2023-05-22 11:12 UTC, Shamarash commented on packages/client/src/components/Game/utils/projectile.ts
> +        return [346, 102, 4, 3];
сделал через Record и обращение к ключу записи, свич убрал

2023-05-23 08:34 UTC, MikeDevice approved these changes

2023-05-23 11:08 UTC, merged