Shamarash/pra 36 add oauth authorization to the project
firetimeloop/battlegrad pull request #22
Opened 2023-06-22 20:15 UTC by Shamarash

Добавил oauth сервис яндекса. К сожалению пока бэкенд яндекс практикум по авторизации работает с ошибкой, данные пользователя при первом входе через oauth отдаются нормально, потом всегда 400 либо 500 ошибка. Поэтому временно после получения токена от oauth яндекс отправляем обычный запрос на авторизацию с логином-паролем с зашитыми тестовыми данными

2023-06-22 20:18 UTC, firetimeloop approved these changes

2023-06-24 08:22 UTC, MikeDevice commented
Правила практикума говорят, что нельзя звать ревьюера, когда CI упал в ПР

2023-06-24 08:22 UTC, MikeDevice requested changes
😰

2023-06-24 09:44 UTC, Shamarash commented
> Правила практикума говорят, что нельзя звать ревьюера, когда CI упал в ПР

прошу прощения, не заметил. поправил

2023-06-26 08:52 UTC, MikeDevice approved these changes
ок, но с вопросиками

2023-06-26 08:52 UTC, MikeDevice commented on packages/client/src/app/api.ts
> +const TEST_PASSWORD = 'Password1234';
если это тестовое -- ок, но никогда в коде не держи секреты

2023-06-26 08:52 UTC, MikeDevice commented on packages/client/src/components/Auth/slice.ts
> +    const response = await axiosYandexApi.post<ILoginResponse>('/oauth/yandex', data);
дублируется `/oauth/yandex/`. Можно вынести в константу

2023-06-26 08:52 UTC, MikeDevice commented on packages/client/src/pages/Login/Login.tsx
> +                onClick={() => {
инлайновые функции писать плохо, потому что так размазывается ответственность (интерфейс и бизнес логика)

2023-06-26 08:52 UTC, MikeDevice commented on packages/client/src/pages/Login/Login.tsx
> +                <BtnText style={{ opacity: isFetching ? '0' : '1' }}>
лучше через css. инлайновые стили нужно использовать как крайняя мера

2023-06-26 12:36 UTC, merged