Oelvg/pra 20 верстка экрана игры начало обратныи
firetimeloop/battlegrad pull request #6
Opened 2023-05-01 16:22 UTC by ElvgOvadykov

### Вёрстка экрана игры Начало
Добавил компонент модального окна, отображение модального окна при начале игры, меню паузы.

2023-05-01 18:21 UTC, firetimeloop commented on packages/client/src/components/Button/Button.tsx
> +  children: ReactNode;
Можно посмотреть в сторону типа FC из реакта, можно будет не заморачиваться с чилдренами. Других компонентов с children тоже касается.

2023-05-01 18:21 UTC, firetimeloop commented on packages/client/src/components/Button/styles/Button.tsx
> +  background-color: #3369f3;
#3369f3 надо наверное в константу вынести или в тему, он много где используется по дизайну

2023-05-01 18:21 UTC, firetimeloop commented on packages/client/src/components/ControlBlock/ControlBlock.tsx
> +import UpArrow from '@icons/up-arrow.svg';
компоненты обязательно с большой буквы, но это же не компоненты)

2023-05-01 18:21 UTC, firetimeloop commented on packages/client/src/components/Modal/Modal.tsx
> +    if (typeof toggleModal === 'function') {
Можно просто if (toggleModal), раз функция это объект и всегда true

2023-05-01 18:21 UTC, firetimeloop commented on packages/client/src/pages/Game/Game.tsx
> +    <Fragment key="Game">
А зачем здесь фрагмент с ключом, что нам это дает?

2023-05-01 18:21 UTC, firetimeloop commented on packages/client/src/pages/Game/Game.tsx
> +      <Modal isVisible={isModalVisible}>
Эту и следующую модалки, наверное, имеет смысл утащить в папку packages/client/src/pages/Game/containers или components в папки StartGameModal и  PauseModal

2023-05-03 20:21 UTC, ElvgOvadykov commented on packages/client/src/components/Button/Button.tsx
> +  children: ReactNode;
Использовал PropsWithChildren<T>

2023-05-03 20:21 UTC, ElvgOvadykov commented on packages/client/src/components/Button/styles/Button.tsx
> +  background-color: #3369f3;
Вынес в тему

2023-05-03 20:21 UTC, ElvgOvadykov commented on packages/client/src/components/ControlBlock/ControlBlock.tsx
> +import UpArrow from '@icons/up-arrow.svg';
Исправил

2023-05-03 20:21 UTC, ElvgOvadykov commented on packages/client/src/components/Modal/Modal.tsx
> +    if (typeof toggleModal === 'function') {
Изменил

2023-05-03 20:21 UTC, ElvgOvadykov commented on packages/client/src/pages/Game/Game.tsx
> +    <Fragment key="Game">
Исправил

2023-05-03 20:21 UTC, ElvgOvadykov commented on packages/client/src/pages/Game/Game.tsx
> +      <Modal isVisible={isModalVisible}>
Вынес в компоненты

2023-05-04 06:28 UTC, firetimeloop approved these changes

2023-05-10 10:14 UTC, MikeDevice requested changes

2023-05-10 10:14 UTC, MikeDevice commented on packages/client/src/assets/icons/up-arrow.svg
вообще правильнее иметь одну стрелку и поворачивать её через цсс. Так ты куда меньше по сети будет трафика гонять (одну картинку быстрее грузить, чем четыре)

2023-05-10 10:14 UTC, MikeDevice commented on packages/client/src/components/Modal/Modal.tsx
> +    if (!isClosable) {
1. это поле лишнее. оно вводит рассинхрон: ты можешь подать isClosable, но не подать toggleModal, и тогда она всё равно не будет закрываться. Делай просто проверку на toggleModal
2. почему toggleModal? Модалка сама себя открыть не может, тут надо closeModal

2023-05-10 10:14 UTC, MikeDevice commented on packages/client/src/pages/Game/Game.tsx
> +        onCloseModal={() => setStartGameModalVisible(false)}
лучше в функцию вынести. не надо инлайнить. с инлайновыми функциями тяжко, когда приходится их менять

2023-05-10 10:14 UTC, MikeDevice commented on packages/client/src/pages/Game/components/PauseModal/PauseModal.tsx
> +        <Button onClick={() => console.log('Закончить игру')}>
инлайновые функции лучше не делай

2023-05-10 10:14 UTC, MikeDevice commented on packages/client/src/pages/Game/components/PauseModal/PauseModal.tsx
> +        </Button>
кнопка с навигацией -- антипаттерн. Тут должен быть Link из пакета react-router. Подробнее тут https://htmlacademy.ru/blog/html/links-or-buttons

2023-05-10 10:14 UTC, MikeDevice commented on packages/client/src/pages/Game/components/StartGameModal/StartGameModal.tsx
> +          <Button onClick={() => onSelectMode(1)}>1 игрок</Button>
инлайны

2023-05-11 10:03 UTC, MikeDevice approved these changes

2023-05-11 10:03 UTC, MikeDevice commented on packages/client/src/components/Modal/Modal.tsx
> +    }
можно проще

```suggestion
    closeModal?.();
```

2023-05-11 19:52 UTC, merged